[package]
name = "rust-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rust_decimal = "1.20"
anyhow = "1.0"
thiserror = "1.0"
derive-new = "0.5.8"